Repository DSC-NITA/HacktoberFest2020, pull requests merged in 2020-10, with the labels that each got.

#4 Fixed the Hacktoberfest offical Link in README.md
  README.md
Labels: good first issue

#15 Made rules clearer
  README.md
Labels: documentation

#10 Added Auto Join Google Meet
  Automation-Scripts/Auto join Google meet.py
Labels: hactoberfest-accepted

#13 String_Matching_Algo_KMP.java
  DSA/Strings/String_Matching_Algo_KMP.java
Labels: enhancement-requested, hactoberfest-accepted

#14 Added a C++ file of Implementation of Stack Using Vector
  DSA/Stacks/Implementation_of_Stack_Using_Vector.cpp
Labels: enhancement-requested, hactoberfest-accepted

#16 Added a new folder and a sorting algo in that folder
  DSA/Algorithms/Sorting-Searching/Sorting/Insertion_Sort.cpp
Labels: hactoberfest-accepted

#21 Python Data Structure Coursera Chapter 7
  Miscellaneous/Coursera/ass7_1/7_1.py
  Miscellaneous/Coursera/ass7_1/data7.txt
  Miscellaneous/Coursera/ass7_2/7_2.py
  Miscellaneous/Coursera/ass7_2/data7_2.txt
Labels: hactoberfest-accepted

#22 Python Data Structure Coursera Chapter 6
  Miscellaneous/Coursera/six_1.py
Labels: hactoberfest-accepted

#25 Merge Sort Algorithm
  DSA/Algorithms/Sorting-Searching/Sorting/MergeSort.java
Labels: hactoberfest-accepted

#23 Added a new sorting algo
  DSA/Algorithms/Sorting-Searching/Sorting/Bubble_Sort.cpp
Labels: hactoberfest-accepted

#24 added c++ implementation of two pointer technique
  DSA/Two-Pointers/find_a_pair_with_given_sum.cpp
Labels: hactoberfest-accepted

#26 Quick Sort
  DSA/Algorithms/Sorting-Searching/Sorting/QuickSort.java
Labels: hactoberfest-accepted

#29 Issue #28 Updated
  Automation-Scripts/Auto Join GoogleMeet/Auto join Google meet.py
Labels: hactoberfest-accepted

#30 Added lcs.py in DSA/Strings
  DSA/Strings/lcs.py
Labels: hactoberfest-accepted

#32 Demonstrating simple queue using python3
  DSA/Queues/SimpleQueue.py
Labels: hacktoberfest-accepted

#31 Added files to folder BIT Manipulation
  DSA/Bit-Manipulation/Right_and_Leftshift.cpp
  DSA/Bit-Manipulation/ith_set_bit.cpp
  DSA/Bit-Manipulation/no_of_set_bits.cpp
Labels: hacktoberfest-accepted, hactoberfest-accepted, modification-requested

#33 Created binary search using recursive function
  DSA/Binary-Search/recursive_binary_search.py
Labels: hacktoberfest-accepted

#36 Added Files Project Euler
  DSA/Bit-Manipulation/GFG_Play_with_OR.cpp
  Miscellaneous/Project_Euler/Project_Euler_1.cpp
  Miscellaneous/Project_Euler/Project_Euler_2.cpp
  Miscellaneous/Project_Euler/Project_Euler_3.cpp
  Miscellaneous/Project_Euler/Project_Euler_4.cpp
  Miscellaneous/Project_Euler/Project_Euler_5.cpp
Labels: hacktoberfest-accepted, modification-requested

#38 Added Tower Of Hanoi to algorithm and more Project Euler files.
  DSA/Algorithms/Recursion-Backtracking/Tower_of_Hanoi.cpp
  Miscellaneous/Project_Euler/Project_Euler_6.cpp
  Miscellaneous/Project_Euler/Project_Euler_8.cpp
Labels: hacktoberfest-accepted

#41 Added HackeRank Challenges folder
  Miscellaneous/Hackerrank Solutions/Cycle_detection.py
  Miscellaneous/Hackerrank Solutions/Equal_stacks.py
  Miscellaneous/Hackerrank Solutions/Full_counting_sort.py
  Miscellaneous/Hackerrank Solutions/LeftRotation.py
  Miscellaneous/Hackerrank Solutions/Little_Panda_Power.py
  Miscellaneous/Hackerrank Solutions/README.md
  Miscellaneous/Hackerrank Solutions/queue_using_two_stacks.py
  Miscellaneous/Hackerrank Solutions/sorting:comparator.py
Labels: hacktoberfest-accepted

#42 Added more files to BIT Manipulation folder.
  DSA/Bit-Manipulation/Change_all_even_bits_to_0.cpp
  DSA/Bit-Manipulation/Missing_number.cpp
  DSA/Bit-Manipulation/Power_of_a_number_greater_than_or_equal_to_n.cpp
Labels: hacktoberfest-accepted

#43 Created Insertion_Operation.c
  DSA/LinkedLists/Insertion_Operation.c
Labels: hacktoberfest-accepted

#44 Created Infix_to_Postfix.cpp
  DSA/Stacks/Infix_to_Postfix.cpp
Labels: hacktoberfest-accepted

#40 program for stack using array in cpp
  DSA/Stacks/program for stack using array in cpp
Labels: hacktoberfest-accepted, modification-requested

#46 Coin change Problem
  DSA/Algorithms/Dynamic-Programming/Coin Change 2.java
Labels: hacktoberfest-accepted, modification-requested

#56 Created Level_order_traversal.cpp
  DSA/Trees/Level_order_traversal.cpp
Labels: hacktoberfest-accepted

#57 Linked list and its ADT
  Linked List/Circluar_Linked__List.c
  Linked List/Concat_LL.c
  Linked List/Count_SumLinked_List.c
  Linked List/Create_LL_using_Insert.c
  Linked List/Create_and_Display_LL.c
  Linked List/Deleteing_LL.c
  Linked List/Deleting_from_LL.c
  Linked List/Doubly_Linked_List.c
  Linked List/Insert_in_LL.c
  Linked List/LinearLinkedList.c
  Linked List/LinkedList_CPP.c
  Linked List/Linked_List.c
  Linked List/Max_LL.c
  Linked List/Merge_LL.c
  Linked List/Polynomial_Linked_List.c
  Linked List/Remove_Duplicate_LL.c
  Linked List/Reverse_LL.c
  Linked List/Search_LL.c
  Linked List/SortedInsert_LL.c
  Linked List/isLoop_LL.c
  Linked List/isSorted_LL.c
Labels: hacktoberfest-accepted

#60 Create N-Queen.cpp
  DSA/Algorithms/Recursion-Backtracking/N-Queen.cpp
Labels: hacktoberfest-accepted

#62 Mirror of a Binary Tree
  DSA/Trees/Mirror_Binary_Tree
Labels: hacktoberfest-accepted

#68 Graph important topics
  DSA/Graphs/bfs.cpp
  DSA/Graphs/krushkal's.cpp
  DSA/Graphs/topological sort.cpp
Labels: hacktoberfest-accepted

#75 Create radixSort
  DSA/Algorithms/Sorting-Searching/Sorting/radixSort
Labels: hacktoberfest-accepted

#67 hackerrank solutions are uploaded
  Miscellaneous/Hackerrank Solutions/Find the Runner-Up Score.py
  Miscellaneous/Hackerrank Solutions/Insertion_Sort-Part2.c
  Miscellaneous/Hackerrank Solutions/hackerrank_insertion_sort1.c
Labels: hacktoberfest-accepted

#71 Added famous N-Queen Backtracking recursion problem
  DSA/Algorithms/Recursion-Backtracking/N-Queen.cpp
  DSA/Trees/All Nodes Distance K in Binary Tree.cpp
Labels: hacktoberfest-accepted, modification-requested

#76 Create ShortestpathGraph.java
  DSA/Graphs/ShortestpathGraph.java
Labels: modification-requested

#79 0-1 Knapsack C++
  DSA/Algorithms/Dynamic-Programming/0-1 Knapsack.cpp
Labels: hacktoberfest-accepted

#80 Kth smallest element using heap
  DSA/Heaps-Maps/Kth smallest element using heap.cpp
Labels: hacktoberfest-accepted

#89 Add files via upload
  DSA/Arrays/find_the_max_value_in_a_bitonic_array.cpp
Labels: hacktoberfest-accepted

#99 Auto-Email using SMTP Library
  Automation-Scripts/Auto Email From CSV/README.md
  Automation-Scripts/Auto Email From CSV/email-script.py
Labels: hacktoberfest-accepted

#100 Flood Fill Algorithm
  DSA/Graphs/Flood-Fill-Algorithm
Labels: hacktoberfest-accepted

#104 Create Check If a Binary Tree is BST
  DSA/Trees/Check _If_BST.cpp
Labels: modification-requested
